### ISSUE TITLE
Fused stack cropped too much

### ISSUE THREAD

**Issue by WhoIsJack** [m-albert/MVRegFus#10]
Yo Marvin (@m-albert),

Been getting back into this with the help of a rotation student.

Having fixed the stuff discussed in #8, optimized the parameters, and switched to a beefy GPU, we now get very nice fusion quality using `raw_input_binning = [1,1,1]`, `mv_final_spacing = np.array([0.4]*3)`, `fusion_method = 'LR'` and `fusion_weights = 'dct'`). 🎉 

However, in the example we've been using for our tests, the final fused stack ends up being cropped too much; about 5% or so of the embryo get cut off on both sides along the y axis. I think this is also something I've seen before with other samples and different settings.

Any thoughts on what's happening and how to avoid it? I should note that each of our input stacks only goes about 60% through the sample, as there's no signal anymore if we go deeper than that (i.e. further away from the objective). Could this be the cause of the issue? Do we need to image all the way through in each view? Or could it be something else? Thanks!

**Comment by m-albert** [comment]
Hey Jonas, great to hear you're getting reasonable reconstruction quality :)

Regarding the cropping: The default setting for determining the output volume is `final_volume_mode = 'sample'`. In this mode, the corners of the output volumes are defined by the first z plane of each input stack. This mode typically works well for four angle acquisitions at 90 degrees and limits the output volume to the important pits. However if you're experiencing problems with it, you could use `final_volume_mode = 'union'` for your reconstruction, which would determine the output volume such that it includes all regions from all input views.

**Comment by WhoIsJack** [comment]
Oooooh! How did we miss this! That's exactly what we need! Thanks! 😆 

We've gone for 3 volumes at 120°. Would you recommend using 4 instead? Or do you mean 4 single views without dual-view fusion? We've been doing dual-view fusion within ZEN already, during acquisition.

**Comment by m-albert** [comment]
> We've gone for 3 volumes at 120°.

That explains why `final_volume_mode = 'sample'` doesn't work well.

> Would you recommend using 4 instead? Or do you mean 4 single views without dual-view fusion?

I guess this is hard to say in general. Four views gives you a more complete sampling of frequencies and helps with defining the output volume automatically. However, of course it means acquiring more data. Dual view fusion within ZEN would typically take the average between the illuminations, so I guess the criterion here would be sth like: if you have comparable image quality between the illuminations across the entire field of view, online fusion makes sense. Otherwise fusing the illuminations offline with a different method makes more sense. There's some support for this around here

https://github.com/m-albert/MVRegFus/blob/1a1eeec5a1a69e2c5f837aa92e812b3ff55ae628/bin/mvregfus_run.py#L54-L69

**Comment by WhoIsJack** [comment]
Ok, many thanks for the advice! Will let you know about the final result. 😉

**Comment by WhoIsJack** [comment]
As you'll have seen from [Zimeng's tweet](https://twitter.com/ZimengWu33/status/1724581214730817999), things are working pretty nicely for us now!  🎉 🎉 🎉 

Both 3 views (with `'union'`) and 4 views (with `'sample'`) are working, though the 4 views option definitely yields a far superior result.

Thanks again for your support! Please feel free to close both this and #8.

**Comment by m-albert** [comment]
Great to hear and thanks for the shoutout in the tweet!
